### ISSUE TITLE
Couldn't download files that have Colon ":" in path

### ISSUE THREAD

**Issue by tarikmsr** [inceptusp/fl_downloader#10]
this issue happened when I tried to download files using this package on Mobile Android application.

**Comment by ctwoon** [comment]
same issue right here

**Comment by inceptusp** [comment]
There was some error message? In which platform? Could you provide an example link?

**Comment by tarikmsr** [comment]
@inceptusp 

# Example:
platform : Mobile Android application
# The code
```
 try{
   String link = 'https://firebasestorage.googleapis.com/v0/b/docbase-52cb6.appspot.com/o/users%2FIidNB2wje8SRFsV6rDNZuQQTRLR2%2F2022%2F26-10%3A3-44-34_IMG_20221001_212346_140.jpg?alt=media';

 await FlDownloader.download(link);
}catch(e){ print("error :$e"); }
```
# Explication:
```
the original link has a Colon :  2022-10-05 16:30.png
it will save in firebase as  https://firebasestorage.googleapis.com/......2022-10-05%2016%3A30.png ......
the colon replaced by '%3A'
so the problem is FlDownloader can't find the link with this form,
unfortunately there isn't any error message
just a message in my phone screen "couldn't download items"
```
 # What I tried
```
I changed to the link to original form using  : Uri.decodeComponent(link)
but same problem            
```

# This is a file link for the test
                            
https://firebasestorage.googleapis.com/v0/b/docbase-52cb6.appspot.com/o/users%2FIidNB2wje8SRFsV6rDNZuQQTRLR2%2F2022%2F26-10%3A3-44-34_IMG_20221001_212346_140.jpg?alt=media

**Comment by inceptusp** [comment]
Right...

First, thanks for the extra information. 😁

After futher investigation with the provided URL, the problem is not only the colon ( : ) , the URL for test that you sent also contains slashes ( / ) encoded as part of the file name... I will push a fix for auto file naming to replace any forbiden carachters on file names with a dash ( - ). In the meantime, you could bypass this issue by providing a custom [fileName] on the `download()` method.

It will be uploaded as part of https://github.com/inceptusp/fl_downloader/pull/8
After the fix, you will know the fileName by getting the last path segment of filePath returned on progessListen event, if you want. Like: 
```dart
final savedFileName = Uri.parse(event.filePath ?? '').pathSegments.last;
```
