### ISSUE TITLE
Error: 	Attribute uses-permission#android.permission.READ_EXTERNAL_STORAGE@maxSdkVersion value=(32)

### ISSUE THREAD

**Issue by korat2511** [inceptusp/fl_downloader#25]
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 7632 bytes (99.5% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
/Users/rutvikkorat/flutter_app/core_pmc/android/app/src/main/AndroidManifest.xml:11:9-35 Error:
	Attribute uses-permission#android.permission.READ_EXTERNAL_STORAGE@maxSdkVersion value=(32) from [:file_picker] AndroidManifest.xml:11:9-35
	is also present at [:fl_downloader] AndroidManifest.xml:12:9-35 value=(29).
	Suggestion: add 'tools:replace="android:maxSdkVersion"' to <uses-permission> element at AndroidManifest.xml:12:5-80 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed : Attribute uses-permission#android.permission.READ_EXTERNAL_STORAGE@maxSdkVersion value=(32) from [:file_picker] AndroidManifest.xml:11:9-35
  	is also present at [:fl_downloader] AndroidManifest.xml:12:9-35 value=(29).
  	Suggestion: add 'tools:replace="android:maxSdkVersion"' to <uses-permission> element at AndroidManifest.xml:12:5-80 to override.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 21s
Running Gradle task 'assembleRelease'...                           82.3s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
![Uploading Screenshot 2024-10-23 at 12.19.10 PM.png…]()

**Comment by LnrdRmj** [comment]
I just added this to my main AndroidManifest:

`<uses-permission
    android:name="android.permission.READ_EXTERNAL_STORAGE"
    android:maxSdkVersion="31"
    tools:replace="android:maxSdkVersion" />`
        
It would be nice to know why the maxSdkVersion of 29 is set tho, since apparently using it is not a good pratice. [Check this](https://stackoverflow.com/questions/29655857/should-i-use-android-maxsdkversion-in-the-manifest-xml-file)

**Comment by inceptusp** [comment]
@LnrdRmj It is not a good practice to apply this parameter to your `activity` or `application` tags or use the `uses-sdk` tag, in this case, the parameter is applied to the `uses-permission` tag to only activate this permission on Android 10 and bellow, and it is there because to access the Downloads folder on Android 10 and bellow the app needs permission to read the external storage which is not true on Android 11 and up...

Since Android 11, Google have allowed you to access the Downloads folder without needing to request permission to do so as if it was a "public" folder... That is why there is this `maxSdkVersion` on this `uses-permission` tag...

Besides, Google Play have strict policies about requesting permission to access user folders since Android 12, this is one more motivation as to "why this is there"...

Even Google themselves [enforces this kind of things](https://developer.android.com/build/manage-manifests#implicit_system_permissions)... If you look the source of the `camera` official package from the flutter team, you'll see they using the same approach to request writing permission on Android 9 and bellow... The problem here is that it is conflicting with other packages that apply the same setting on their `uses-permission` tags for the same permission as me... I'll see how can I change it to not conflict with another packages in the future... :) thx
