### ISSUE TITLE
Android - java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by dubocr** [inceptusp/fl_downloader#4]
Hello,

For some download, plugin crash with `java.lang.ArithmeticException: divide by zero`

In file FlDownloaderPlugin.kt line 172, the test `if (total >= 0)` must be updated to protect `progress = (downloaded * 100L / total).toInt()`

Great plugin.

Thanks for your work.

**Comment by inceptusp** [comment]
You're right. 

We have this bug tracked for fix, but with low priority for now. There is **two** bigger issues on iOS that is high priority because we are seeing it show up in buckets on crashlytics with our production app that uses this plugin, but we haven't been able to replicate it in our development envs. =(

Thanks for the feedback and we will fix it. =)

**Comment by inceptusp** [comment]
A contributor fixed this.
